### ISSUE TITLE
Issue on page /statistics/multiple.html

### ISSUE THREAD

**Issue by benstr4** [statisticalbiotechnology/dsbook#10]
Introduction, first paragraph. 
Saying that the likelihood of obtaining false positives increases with the amount of tests conducted might not be the most precise wording and might be confusing. I believe something like "the probability of obtaining at least one false positive increases" or "the likelihood of obtaining a false positive increases" would be easier to understand and more precise; as it is not the probability of false positive per test that gets increased.

**Comment by percolator** [comment]
I agree. I don't like the wording. I changed it to 

"In high-throughput biology, analysis often involves testing a large number of hypotheses simultaneously. This is common in fields like genomics, transcriptomics, and proteomics, where experiments might involve thousands of genes or proteins being tested for associations with a condition or trait. A key challenge here is multiple hypothesis testing: when many tests are conducted, the probability of obtaining false positives increases because even a small chance of error for each test can accumulate across thousands of tests, resulting in a substantial number of false discoveries."

Fixed with 0d93c92d14176240a7b5a2e4ec44e9a735de7693
